### ISSUE TITLE
Editing posts breaks links, images, embed. Inserts double quotes.

### ISSUE THREAD

**Issue by sks-zigzag** [Asgaros/asgaros-forum#356] opened 2022-08-24 23:45 UTC
There appears to be a problem with editing a post within the Asgaros forum plugin. Editing a post will break the links, images, or embeds. I noticed when it comes to links, double quotes would appear when I would look at the source code within the editor. This does not happen on wordpress when posting or other plugins. 

I am also using elementor and profilegrid for the membership plugin. I have disabled both, and I still encounter the same problem.

![Screenshot 2022-08-24 162327](https://user-images.githubusercontent.com/112035162/186543014-3c370933-8a07-4b7c-9e5a-8f48d3991d20.png)
![Screenshot 2022-08-24 162451](https://user-images.githubusercontent.com/112035162/186543023-c1b56988-746e-4705-9e11-ca2ce2bd9c8e.png)

Edit:

It appears to be the same problem [as this user](https://www.asgaros.de/support/topic/doubling-quotes-in-topic-source-code/), but I can't even retrieve my password on the site because it doesn't seem to be sending out emails. i even tried a different email from a different provider. Checked spam also.

**Comment by Asgaros** [comment] 2023-03-31 03:59
Hello @sks-zigzag 

Sorry for the late reply but I wonder if you still have this issue? I cannot really reproduce it and also didnt get any other reports of that anymore.

**Comment by Asgaros** [comment] 2023-08-14 02:53
Since I didn't get any similar reports and there is no feedback, I will close this issue.

**Closed by Asgaros** 2023-08-14 02:53 UTC
